New standalone readalong XML format
ReadAlongs/Studio pull request #142
Opened 2023-01-31 21:00 UTC by dhdaines

- alignments are (optionally) added as attributes
- there is a DTD
- we still generate SMIL just in case

2023-02-07 18:15 UTC, joanise reviewed
Wow, this is much simpler than I expected it to be. I still want to test it locally, but it looks good.

2023-02-07 18:19 UTC, dhdaines commented on readalongs/static/readalong.dtd
> + xml:lang CDATA #IMPLIED
ah right, I need to fix that (the DTD doesn't really block anything because we don't do validation, but it should still be in sync with the code)

2023-02-07 18:20 UTC, dhdaines commented on readalongs/static/readalong.dtd
> + xml:lang CDATA #IMPLIED
reminds me, I also need to add `<span>` to the DTD for the subword stuff

2023-02-07 18:28 UTC, joanise commented on readalongs/static/readalong.dtd
> + xml:lang CDATA #IMPLIED
right, good idea!

2023-02-07 18:39 UTC, joanise commented
Question about web_api.py`: the `CovertRequest` class still has a SMIL element, and so the `/convert_alignment` endpoint still expects a smil file. Will that code still work? Or should it be changed to read the time and dur in the .ras file instead?

2023-02-07 18:46 UTC, joanise commented
I think you've already commented about that, but merging this PR will require to have your parallel PR in Web-C published "at the same time", so that:
 - the single-file HTML can be generated correctly, and
 - the generated `index.html` file can point to the right version of the web-c.

So we'll have to do some careful coordination here.

2023-02-07 19:13 UTC, dhdaines commented
> I think you've already commented about that, but merging this PR will require to have your parallel PR in Web-C published "at the same time"

Yes, not only that but the Web-C will have to be published to NPM and unpkg at the same time.  We need to bump at least the minor version number (since it's an 0.x release that is probably sufficient)

2023-02-07 19:14 UTC, dhdaines commented
> Question about `web_api.py`: the `ConvertRequest` class still has a SMIL element, and so the `/convert_alignment` endpoint still expects a smil file. Will that code still work? Or should it be changed to read the time and dur in the .ras file instead?

Ohh, good catch. I may have started doing that in a previous iteration of this PR, I'll update it before merging

2023-02-07 23:18 UTC, roedoejet requested changes
This is awesome @dhdaines - thanks! There are still a few things:

- can you remind me why we don't use .ras?
- I don't see anywhere that versioning of the DTD is handled, but maybe I just missed it. I would like to see a way for us to support various versions of our .ras format as it changes.
- it would be great to add some docs around what the RAS format is and publish versioned examples of the DTD

2023-02-07 23:27 UTC, dhdaines commented
> This is awesome @dhdaines - thanks! There are still a few things:
> 
> * can you remind me why we don't use .ras?

Mainly because if it gets served by a webserver, it won't get the right MIME type by default, likewise in the Windows Explorer and MacOS Finder (Linux will probably read the first 6 bytes and realize it is XML, but that's a minority opinion :) )

> * I don't see anywhere that versioning of the DTD is handled, but maybe I just missed it. I would like to see a way for us to support various versions of our .ras format as it changes.

Yes, that's a bit of a mystery to me how to version a DTD, but for the moment I can just put a version number in the filename and a comment...

> * it would be great to add some docs around what the RAS format is and publish versioned examples of the DTD

Good idea... one thing to note is that, I don't think we will ever really *use* the DTD, because parsing XML as actual XML (rather than as HTML5) is a lot of trouble for nothing with the namespaces and the declarations and the entities and the hrgl brlgl sharp teeth and biting.

2023-02-08 12:21 UTC, dhdaines commented
> > This is awesome @dhdaines - thanks! There are still a few things:
> > 
> > * can you remind me why we don't use .ras?
> 
> Mainly because if it gets served by a webserver, it won't get the right MIME type by default, likewise in the Windows Explorer and MacOS Finder (Linux will probably read the first 6 bytes and realize it is XML, but that's a minority opinion :) )

Per our conversation last night I'm making a note here - we will use .ras after all, since in general we *do* have control over the MIME type, either through a data URL or application server config.

2023-02-08 17:53 UTC, dhdaines commented on readalongs/align.py
> +        xml_path (str): Path to XML input file in RAS format
I put a note about the DTD, and it's now described a bit better in the documentation...

2023-02-08 17:53 UTC, dhdaines commented on readalongs/templates/export.html
> +        {# <read-along readalong="/file/aligned.xml" audio="/file/aligned{{data.audio_ext}}"></read-along> #}
done :)

2023-02-08 18:21 UTC, dhdaines commented
choosing to ignore codecov here, the decreases in coverage are not catastrophic and don't seem to be things we care much about.

2023-02-08 18:35 UTC, joanise commented
> choosing to ignore codecov here, the decreases in coverage are not catastrophic and don't seem to be things we care much about.

Yeah, I try to keep coverage going up on every PR, but it's certainly not a requirement. The report is weird, though, with 89% of the patch being covered, more than the 81% baseline, yet the project coverage is declining. It's certainly nothing to worry about anyway.

2023-02-08 18:37 UTC, merged